AUDITOR_MIN_LENGTH = 1
AUDITOR_MAX_LENGTH = 50

TITLE_MIN_LENGTH = 1
TITLE_MAX_LENGTH = 50

QUESTION_MIN_LENGTH = 1
QUESTION_MAX_LENGTH = 50

COMMENT_MIN_LENGTH = 1
COMMENT_MAX_LENGTH = 50

SEVERITY_VALUES = [
    "RED",
    "YELLOW",
    "GREEN",
]

KIVY_REQUIRED_VERSION = "1.11.1"

TEST_DB = "testdb"