FloatLayout:
    Label:
        text: 'Login'
        font_size: 40
        pos: 0, 150
    Button:
        text: "Admin"
        font_size: 30
        size: 250, 200
        size_hint: None, None
        pos: 150, 175
    Button:
        text: "Auditor"
        font_size: 30
        size: 250, 200
        size_hint: None, None
        pos: 400, 175
    Button:
        text: 'Exit'
        font_size: 30
        size: 500, 100
        size_hint: None, None
        pos: 150, 100

